/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia_cliente;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.parser.JSONParser;
import serviciosweb.Despacho;
import serviciosweb.Despacho_Service;
import serviciosweb.Paciente_Service;
import serviciosweb.Paciente;
import serviciosweb.Receta_Service;
import serviciosweb.Receta;
import serviciosweb.Cita;
import serviciosweb.Cita_Service;
import serviciosweb.SQLException_Exception;
import org.json.*;

/**
 *
 * @author julian
 */
public class despachar_medicamento extends javax.swing.JFrame {

    /**
     * Creates new form despachar_medicamento
     */
    public despachar_medicamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        result_txt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Despachar Medicamento");

        jLabel2.setText("DPI");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(result_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result_txt)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dpi = jTextField1.getText();
        Paciente_Service ps = new Paciente_Service();
        final Paciente pa = ps.getPacientePort();
        Receta_Service rs = new Receta_Service();
        final Receta re = rs.getRecetaPort();
        Cita_Service cs = new Cita_Service();
        final Cita ci = cs.getCitaPort();

        try {
            System.out.println("Buscando id");
            String respuesta = pa.obtenerIdPaciente(dpi);
            System.out.println(respuesta);
            if (respuesta.equals("{\"error\"}")) {
                JOptionPane.showMessageDialog(null, "Error, DPI no existe");
            } else {
                System.out.println("Buscando receta");
                String cr = re.obtenerIdReceta(respuesta);
                if (cr.contains("error")) {
                    JOptionPane.showMessageDialog(null, "No tiene Receta por Despachar");
                } else {
                    JSONObject json = new JSONObject(cr);
                    String idReceta = (String) json.get("receta");
                    String idCita = (String) json.get("cita");

                    String Paciente = pa.consultarPaciente(dpi);
                    JSONObject pac = new JSONObject(Paciente);
                    String nombre = (String) pac.get("nombre");
                    String meds = re.consultarReceta(idReceta);//Recibo Medicamentos
                    String envio = "{\n \"nombre\":\"" + nombre + "\"," + meds.substring(1);
                    System.out.println(envio);
                    Despacho_Service ds = new Despacho_Service();
                    final Despacho d = ds.getDespachoPort();
                    String res = d.despachoMed(envio);
                    System.out.println(res);
                    if (res.contains("error")) {

                    } else {
                        System.out.println(ci.updateRealizada(idCita));
                    }
                    JSONObject fac = new JSONObject(res);
                    String total = (String) fac.getString("total");
                    Iterator<?> keys = fac.keys();
                    int z = 0;
                    String mostrar = "Medicamento -- Cantidad -- Precio -- SubTotal\n";
                    while (keys.hasNext()) {
                        String key = (String) keys.next();
                        if (fac.get(key) instanceof JSONObject) {
                            JSONObject child = (JSONObject) fac.get(key);
                            String sub = child.get("subtotal").toString();
                            String medicamento = child.get("medicamento").toString();
                            String cantidad = child.get("cantidad").toString();
                            String precio = child.getString("precio");
                            mostrar += medicamento + "--" + cantidad + "--" + precio + "--" + sub + "\n";
                        }
                    }
                    mostrar += "---------------------------------- " + total;
                    jTextArea1.setText(mostrar);

                }

            }
        } catch (SQLException_Exception ex) {
            Logger.getLogger(crear_medicamento.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(despachar_medicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(despachar_medicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(despachar_medicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(despachar_medicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new despachar_medicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel result_txt;
    // End of variables declaration//GEN-END:variables
}
